/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_digitalcodex_io_TunTap */

#ifndef _Included_dev_digitalcodex_io_TunTap
#define _Included_dev_digitalcodex_io_TunTap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_digitalcodex_io_TunTap
 * Method:    tuntap_setup
 * Signature: (ILjava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_dev_digitalcodex_io_TunTap_tuntap_1setup
  (JNIEnv *, jobject, jint, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
